max_length: 140
learning_rate: 0.0001
batch_size: 64
num_keep: 1024
experience_loop: 2
experience_replay: 64
lr_z: 0.001
beta: 50
num_jobs: 1
valid_only: False
use_retrosynthesis: True
max_retro_steps: 3
retro_env: stock
sa_threshold: 3.0
reshape_reward: False
filter_unsynthesizable: True
aux_loss: relative_logp
aux_coefficient: 0.001
max_norm: 10.0
